config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :find_kitten, only: [:edit, :show, :update, :destroy]
  
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end
  
  def show
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end
  
  def new
    @kitten = Kitten.new
  end
  
  def edit

  end
  
  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Congratulations! Kitten saved!"
      redirect_to kittens_path
    else
      flash.now[:danger] = "Please fix the errors!"
      render :new
    end
  end
  
  def update
    if @kitten.update(kitten_params)
      flash[:success] = "The kitten info has been updated!"
      redirect_to kittens_path
    else
      flash.now[:danger] = "The information provided couldn't be saved!"
      render :edit
    end
  end
  
  def destroy
    @kitten.destroy
    flash[:success] = "The kitten was deleted!"
    redirect_to kittens_path
  end
  
  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
    
    def find_kitten
      @kitten = Kitten.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_error_messages.html.erb
<% if @kitten.errors.any? %>
	The form contains <%= pluralize(@kitten.errors.count, "error") %>.
	<ul>
		<% @kitten.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>

  <%= render 'error_messages' %>
   
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>
  <br />
  <%= f.label :softness %>
  <%= f.text_field :softness %>
  <br />
  <%= f.submit "Save kitten" %>
  
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten info</h1>
<%= render 'form' %>

<%= link_to "Home", kittens_path %>
<%= link_to "Delete kitten", kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/kittens/index.html.erb
<h1>All kittens</h1>
<% @kittens.each do |kitten| %>
  <p>Name: <%= link_to kitten.name, kitten_path(kitten) %> </p>
  <p>Age: <%= kitten.age %></p>
  <p>Cuteness: <%= kitten.cuteness %></p>
  <p>Softness: <%= kitten.softness %></p>

  <%= link_to "Edit info", edit_kitten_path(kitten) %>      
  <%= link_to "Delete kitten", kitten_path(kitten), method: :delete, data: { confirm: "Are you sure?" } %>
  <hr>
<% end %>

<%= link_to "Create new kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Edit info", edit_kitten_path(@kitten) %>      
<%= link_to "Delete kitten", kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

<%= yield %>

</body>
</html>